data_poc = [
['lexeme from RDF data', 'definition from RDF data', 'keyword fr', 'keyword engl'],

    # Linné

['anemoine', 'sorte de renonculacées à fleurs violettes, dite aussi coquelourde, passe-fleur ou pulsatille (anemone pulsatilla L.)', 'anemone pulsatilla', 'anemone pulsatilla'],
['date2#datier', 'palmier de l’Afrique du Nord et du Moyen-Orient qui produit les dattes, Phœnix dactylifera L., dattier', 'Phœnix dactylifera', 'Phœnix dactylifera'],
['faverole', 'petite plante dicotylédone, de la famille des Plantaginaceae, caractérisée par une tige plus ou moins dressée, par des feuilles opposées, ovales, par des fleurs bleues, fruit en capsule, vivant dans des lieux humides, aux bords des lacs, véronique des ruisseaux (Veronica beccabunga L.)', 'Veronica beccabunga', 'Veronica beccabunga'],
['feve', 'plante annuelle herbacée de la famille des Légumineuses (Fabaceae) pouvant dépasser 1 mètre de hauteur, qui a de grosses gousses contenant des graines comestibles de forme ovale et aplatie, fève maraîchère (Vicia faba L.); la graine de cette plante', 'Vicia faba', 'Vicia faba'],
['feve', 'plante herbacée de la famille des Fabaceae qui peut atteindre 60 centimètres de hauteur, à fleurs d’un blanc jaunâtre et des fruits en forme de gousses pendantes de huit centimètres, attachées aux aisselles des feuilles, renfermant dix à vingt graines anguleuses de couleur brun clair qui dégagent une odeur caractéristique, fenugrec (Trigonella foenum-graecum L.)', 'Trigonella foenum-graecum', 'Trigonella foenum-graecum'],
['feve', 'plante aquatique de la famille des Nélumbonacées avec des fleurs de couleur blanc rosé, de 15 à 30 cm de diamètre, des feuilles arrondies, peltées, pouvant mesurer jusqu’à 50 cm de diamètre et pouvant flotter sur l’eau, et avec des graines à péricarpe très dur et très étanche, fève d’Égypte, Lotus sacré ou Lotus d’Orient (Nelumbo nucifera, Nymphæa Nelumbo L.); la graine de cette plante', 'Nymphæa Nelumbo', 'Nymphæa Nelumbo'],
['feve', 'genre de plantes de la famille des Fabaceae regroupant de très nombreuses espèces dont beaucoup sont toxiques et dont beaucoup sont cultivées pour leur graines comestibles et riches en protéines (notamment les lupins doux qui ont moins d’alcaloïdes) et pour leur capacité d’améliorer les sols, lupin (Lupinus L.)', 'Lupinus', 'Lupinus'],
['figue', 'fruit comestible de couleur violette, marron-rouge, verdâtre ou jaune, et à pulpe molle dans l’état mûr, qui est le fruit du figuier, l’arbre de la famille des Moracées et du genre Ficus (Ficus carica L.), figue', 'Ficus carica', 'Ficus carica'],
['menit', 'nom arabe de la chélidoine ou grande éclaire (Chelidonium majus L.), plante de la famille des papavéracées', 'Chelidonium majus', 'Chelidonium majus'],
['quesafist', 'sorte de plante, canéficier (Cassia fistula)', 'Cassia fistula', 'Cassia fistula'],
['robert', 'plante annuelle ou bisanuelle de la famille des Géraniacées, Géranium Herbe à Robert (Geranium robertianum L.)', 'Geranium robertianum', 'Geranium robertianum'],
['roche1', 'sorte de poisson d’eau douce, commun, qui vit en Europe et en Asie occidentale, avec une chair très appréciée, gardon (Rutilus rutilus L.)', 'Rutilus rutilus', 'Rutilus rutilus'],
['titolose', 'plante herbacée bulbeuse de la famille des Amaryllidaceae, ail des vignes (Allium vineale)', 'Allium vineale', 'Allium vineale'],
['turmie', 'arbre de la famille des Rosacées, cormier ou sorbier domestique (Sorbus domestica L.)', 'Sorbus domestica', 'Sorbus domestica'],
['valeros', 'espèce de grand mammifère marin, unique représentant de son genre Odobenus et de sa famille des Odobenidae, qui peut peser jusqu’à deux tonnes et qui a des moustaches drues et une allure massive, morse (Odobenus rosmarus)', 'Odobenus rosmarus', 'Odobenus rosmarus'],
['vascher', 'espèce d’échassier, de la famille des ardéidés, Héron garde-bœufs (Bubulcus ibis L.)', 'Bubulcus ibis', 'Bubulcus ibis'],
['vert#verdiere', 'espèce de passereaux partiellement migrateur, très répandu, de la famille des Fringillidés, qui atteint une longueur de 16 cm, verdier d’europe (Chloris chloris L.)', 'Chloris chloris', 'Chloris chloris'],
['vesele', 'le plus petit mammifère de la famille des mustélidés, aussi le plus petit mammifère carnivore d’Europe avec une taille d’environ 20 cm pour moins d’une centaine de grammes, belette (Mustela nivalis L.)', 'Mustela nivalis', 'Mustela nivalis'],
['villain1', 'espèce de poisson d’eau douce très fréquente en Europe de la famille des cyprinidés, chevesne ou chevaine, meunier (Squalius cephalus L.)', 'Squalius cephalus', 'Squalius cephalus'],
['vïole#vïoletee', 'plante herbacée de la famille des Lythraceae très répandue dans presque toute l’Europe, qui vit à proximité des cours d’eau où elle forme de longues inflorescences rose pourpré, salicaire commune (Lythrum salicaria L.)', 'Lythrum salicaria', 'Lythrum salicaria'],
['vïole#vïolier', 'genre de plantes herbacées vivaces de la famille des Violaceae qui ont un usage principalement ornemental et dont les variétés odorantes servent en parfumerie et en confiserie, violette ou pensée (Viola L.)', 'Viola', 'Viola'],
['vione', 'arbuste de 4 à 5 mètres de hauteur dont les fleurs blanc-crème de 5 mm forment en avril-juin des inflorescences en ombelles denses, viorne lantane (Viburnum lantana L.)', 'Viburnum lantana', 'Viburnum lantana'],
['vione', 'plante ligneuse grimpante de la famille des Renonculacées, clématite des haies ou Clématite vigne-blanche (Clematis vitalba L.)', 'Clematis vitalba', 'Clematis vitalba'],
['viticele', 'espèce de plantes grimpantes monocotylédones de la famille des ignames Dioscoreaceae, tamier commun ou herbe aux femmes battues (Dioscorea communis L.)', 'Dioscorea communis', 'Dioscorea communis'],
['vivet', 'espèce de poissons marins de la famille des Trachinidae qui mesure environ 18 cm et qui se trouve dans les eaux peu profondes, qui est doté de venin et dont la piqûre peut être douloureuse pendant plusieurs semaines, petite vive (Echiichthys vipera)', 'Echiichthys', 'Echiichthys'],
['voison', 'le plus petit mammifère de la famille des mustélidés avec une taille d’environ 20 cm pour moins d’une centaine de grammes seulement, belette d’Europe (Mustela nivalis L.)', 'Mustela nivalis', 'Mustela nivalis'],
['walewort', 'plante de la famille des Adoxaceae, herbacée et mesurant 1 à 2 m de haut, à odeur fétide, et dont les baies noires peuvent être toxiques, sureau hièble, petit sureau, hièble (Sambucus ebulus L.)', 'Sambucus ebulus', 'Sambucus ebulus'],
['wildewolde', 'plante herbacée bisannuelle de la famille des Résédacées commune en Europe occidentale et méridionale, qui est cultivée comme plante tinctoriale, réséda des teinturiers ou réséda jaunâtre (Reseda luteola L.)', 'Reseda luteola', 'Reseda luteola'],
['wodesoure', 'plante herbacée pérenne de la famille des Oxalidacées qui fleurit d’avril à mai et qui pousse surtout en sous-bois, oseille des bois, oxalide des bois (Oxalis acetosella L.)', 'Oxalis acetosella', 'Oxalis acetosella'],
['wodlark', 'espèce d’oiseaux. Comme toutes les alouettes elle appartient à la famille des Alaudidae, alouette lulu (Lullula arborea L.)', 'Lullula arborea', 'Lullula arborea'],

    # EinWort

['eage#soseage', 'minorité', 'minorité', 'minority'],
['ebene', 'ébène', 'ébène', 'ebony'],
['esperit#esperite', 'souffle', 'souffle', 'breath'],
['esperit#esperitene', 'esprit', 'esprit', 'spirit'],
['haïr#hé', 'haine', 'haine', 'hatred'],
['lechier1#leche', 'plaisir', 'plaisir', 'pleasure'],
['lechier1#lechefroie', 'lèchefrite', 'lèchefrite', 'griddle'],
['lechier1#lechement', 'flatterie', 'flatterie', 'flattery'],
['lechier1#lecherant', 'lecheur', 'lecheur', 'licker'],
['lechier1#lecheüre', 'gourmandise', 'gourmandise', 'gluttony'],
['leçon', 'leçon', 'leçon', 'lesson'],
['liquor', 'liqueur', 'liqueur', 'liquor'],
['lire#liseor', 'lecteur', 'lecteur', 'reader'],
['lire#liseresse', 'lectrice', 'lectrice', 'reader'],
['lire#lisure', 'lecture', 'lecture', 'reading'],
['laissier#laisse', 'strophe', 'strophe', 'stanza'],
['laissier#relaisse', 'rémission', 'rémission', 'remission'],
['laissier#eslaisse', 'élan', 'élan', 'momentum'],
['pape#sorpape', 'anti-pape', 'anti-pape', 'anti-pope'],
['pere', 'père', 'père', 'father'],
['pere#padraste', 'parâtre', 'parâtre', 'stepfather'],
['pere#avantpere', 'ancêtre', 'ancêtre', 'ancestor'],
['pié', 'pied', 'pied', 'foot'],
['pié', 'fantassin', 'fantassin', 'infantryman'],
['pié#empietement', 'usurpation', 'usurpation', 'usurpation'],
['pié#peage', 'coup', 'coup', 'cut'],
['pie1#pigace', 'pointe', 'pointe', 'point'],
['pie1#pivernaus', 'goutte', 'goutte', 'drop'],
['pie1#pivois', 'vin', 'vin', 'wine'],
['tord#entorse', 'contorsion', 'contorsion', 'contortion'],

    # LetztWort

['dars#darset', 'poisson d’eau douce, plutôt petit, appartenant à la famille des Cyprinidae, vandoise?', 'vandoise?', 'Leuciscus leuciscus'],
['date#datil', 'fruit du palmier dattier, datte', 'datte', 'date'],
['date1', 'excrément humain ou animal liquide qui est évacué par l’urètre, urine', 'urine', 'urine'],
['date2#datelier', 'palmier de l’Afrique du Nord et du Moyen-Orient qui produit les dattes, dattier', 'dattier', 'date palm'],
['eage#deseagement', 'état d’une personne qui n’a pas encore atteint l’âge où elle sera légalement considérée comme pleinement capable et responsable de ses actes, minorité', 'minorité', 'minority'],
['eage#eagement', 'émancipation, majorité', 'majorité', 'majority'],
['eaune', 'plante médicinale et comestible de la famille des composées, aunée', 'aunée', 'elecampane'],
['ebenus', 'bois de l’ébénier, ébène', 'ébène', 'ebony'],
['ebil', 'plante herbacée de la famille des renonculacées, dont la racine a des propriétés purgatives et vermifuges, ellébore', 'ellébore', 'helleborus'],
['engrot', 'altération organique ou fonctionnelle de l’état de santé se manifestant par un ensemble de signes et de symptômes (se référant au corps ou à l’âme), maladie', 'maladie', 'disease'],
['esperit', 'souffle (du vent), respiration', 'respiration', 'respiration'],
['esperit', 'principe de la vie incorporelle de l’être humain, âme', 'âme', 'soul'],
['esperit', 'diable, démon', 'démon', 'devil'],
['esperit', 'jugement, intelligence', 'intelligence', 'intelligence'],
['esperit#espirt', 'esprit, fantôme', 'fantôme', 'ghost'],
['fable', 'phrase qui, sous une forme figée, exprime une expérience ou un conseil, proverbe', 'proverbe', 'proverb'],
['festre', 'abouchement anormal d’une cavité dans une autre donnant passage de façon continue à un produit physiologique (urine, matière fécale, bile, etc.) ou purulent qui s’écoule à la surface du corps (ayant une forme qui ressemble à un ulcère) ou dans une cavité interne, fistule', 'fistule', 'fistula'],
['fiel', 'liquide verdâtre et amer qui est contenu dans la vésicule biliaire, bile', 'bile', 'bile'],
['fiel', 'dans l’humorisme, celle des quatre humeurs cardinales qui est sécrétée par la rate, qui a les qualités ‘froid’ et ‘sec’ et qui gouverne la mélancolie dans le corps, bile noire', 'bile noire', 'black bile'],
['fiel', 'réservoir musculo-membraneux, situé à la face antérieure du foie et qui emmagasine la bile, vésicule biliaire', 'vésicule biliaire', 'gallbladder'],
['fiel', 'sentiment de tristesse accompagné de mauvaise humeur et qui est lié à une humiliation, une déception, une injustice ou sim., amertume', 'amertume', 'bitterness'],
['figue#figuier', 'arbre qui produit la figue, figuier', 'figuier', 'fig tree'],
['haïr#haïf', 'celui qui est haïssable, ennemi', 'ennemi', 'enemy'],
['lire#enleçoner', 'instruit, élève', 'élève', 'student'],
['mal1#malage', 'mal, malaise, maladie', 'maladie', 'sickness'],
['pape', 'chef de l’Église catholique romaine et évêque de Rome, pape', 'pape', 'pope'],
['roche1', 'désignation qui regroupe plusieurs types de poissons cartilagineux, raie', 'raie', 'stingray'],
['roche1#rochaut', 'sorte de poisson de la famille des Labridés, à dentition double et lèvres épaisses, qui vit dans les eaux peu profondes des côtes rocheuses et dont existent plusieures espèces, labre', 'labre', 'wrasse'],
['roe', 'pièce de forme circulaire qui en tournant sur un essieu, communique le mouvement à une véhicule, roue', 'roue', 'wheel'],
['roe#rodenc', 'trace creusée par les roues des voitures dans le sol, ornière', 'ornière', 'rut'],

    # GenusProximum

['barbe#barbiolete', 'espèce d’animal de l’Inde', 'animal', 'animal'],
['calaint', 'espèce de drogue', 'drogue', 'drug'],
['caraque', 'espèce de navire', 'navire', 'ship'],
['ebe', 'mouvement de la marée descendante, reflux; durée de ce reflux', 'mouvement', 'movement'],
['ebe', 'laps de temps qui comprend la durée d’une marée', 'temps', 'time'],
['ebe#eber', 'être au reflux (de la mer)', 'reflux', 'reflux'],
['ebil', 'plante herbacée de la famille des renonculacées, dont la racine a des propriétés purgatives et vermifuges, ellébore', 'plante herbacée', 'plant'],
['ebrios', 'qui est physiquement et mentalement troublé par la surconsommation de boissons alcooliques, ivre', 'alcool', 'alcohol'],
['ecidoiare', 'rhizome de la zédoaire (plante herbacée rhizomateuse vivace du genre Curcuma, de la famille des Zingibéracées, Curcuma zedoaria Roscoe) comestible et ayant une saveur qui rappelle le gingembre avec un arrière-goût très amer, utilisé comme substance médicinale aidant à la digestion, soulageant les coliques et purifiant le sang', 'rhizome', 'rhizome'],
['elebre#elebrentire', 'sorte de médicament', 'médicament', 'medication'],
['engrot1#engrot2', 'altération organique ou fonctionnelle de l’état de santé se manifestant par un ensemble de signes et de symptômes (se référant au corps ou à l’âme), maladie', 'santé', 'health'],
['fable', 'phrase qui, sous une forme figée, exprime une expérience ou un conseil, proverbe', 'phrase', 'phrase'],
['fable', 'récit inventé plutôt que réel', 'récit', 'narrative'],
['fable', 'phrase qui, sous une forme figée, exprime une expérience ou un conseil, proverbe', 'phrase', 'phrase'],
['fable#fablel', 'conte populaire en vers octosyllabes au caractère satirique ou moral', 'conte', 'narrative'],
['faucille', 'instrument formé d’une étroite lame d’acier lisse ou dentelée, courbée en demi-cercle, montée sur une poignée et qui sert à couper l’herbe, les céréales, etc.', 'instrument', 'instrument'],
['faude1', 'tas de bois recouvert d’herbe ou de feuillage, qu’on carbonise pour faire du charbon de bois, meule', 'bois', 'wood'],
['festre', 'conduit à section plus ou moins arrondie (en matière rigide, flexible ou souple) destiné à faire passer un liquide ou un gaz, tuyau', 'conduit', 'pipe'],
['festre', 'abouchement anormal d’une cavité dans une autre donnant passage de façon continue à un produit physiologique (urine, matière fécale, bile, etc.) ou purulent qui s’écoule à la surface du corps (ayant une forme qui ressemble à un ulcère) ou dans une cavité interne, fistule', 'abouchement', 'cavity'],
['festre', 'instrument de musique fait d’une tige de roseau dont la moelle a été dégagée et qui a été trouée (d’un nombre variable de trous), sorte de flûte ou de pipeau', 'instrument de musique', 'musical instrument'],
['fiel', 'liquide verdâtre et amer qui est contenu dans la vésicule biliaire, bile', 'liquide', 'liquid'],
['fiel', 'dans l’humorisme, celle des quatre humeurs cardinales qui est sécrétée par la rate, qui a les qualités ‘froid’ et ‘sec’ et qui gouverne la mélancolie dans le corps, bile noire', 'humeur', 'temperament'],
['fiel', 'réservoir musculo-membraneux, situé à la face antérieure du foie et qui emmagasine la bile, vésicule biliaire', 'réservoir', 'reservoir'],
['fiel', 'sentiment de tristesse accompagné de mauvaise humeur et qui est lié à une humiliation, une déception, une injustice ou sim., amertume', 'sentiment', 'feeling'],
['figure', 'signe qui représente un chiffre', 'signe', 'sign'],
['porter#portepiece', 'sorte d’outil de cordonnier', 'outil', 'tool'],
['tide#tideman', 'espèce de douanier qui attend la marée haute pour faire les bâteaux arrivant acquitter les impôts', 'douanier', 'customs officer'],
['timbre1', 'espèce de tambour, tambourin', 'tambour', 'drum'],
['tombe#tomberel3', 'espèce de machine de guerre', 'machine de guerre', 'war machine'],
['zecharr', 'espèce de faucon', 'faucon', 'falcon']
]

